version: '3'
services:
  app:
    image: docker-nextjs
    build:
      dockerfile: Dockerfile
    ports:
       - 3000:3000
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videohub
    ports:
      - "3306:3306"
  