version: '3'
services:
  app:
    image: nextjs-docker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/var/movable/app
      - /var/movable/app/node_modules
      - /var/movable/app/.next
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'videohub'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'video'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: /prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  
volumes: #define our mysql volume used above
  mysql:
