module.exports = {
    PERMISSION_VIDEOHUB_PUSHBUTTONS_SCHEDULE: "VIDEOHUB_PUSHBUTTONS_SCHEDULE",
    PERMISSION_VIDEOHUB_PUSHBUTTONS_EDIT: "VIDEOHUB_PUSHBUTTONS_EDIT",
    PERMISSION_VIDEOHUB_EDIT: "VIDEOHUB_EDIT",
    PERMISSION_USER_EDIT: "USER_EDIT",
    PERMISSION_ROLE_EDIT: "ROLE_EDIT",
    toggleablePermissions: ["VIDEOHUB_EDIT", "VIDEOHUB_PUSHBUTTONS_EDIT", "VIDEOHUB_PUSHBUTTONS_SCHEDULE"],
}