module.exports = {
    PERMISSION_VIDEOHUB_OUTPUT_SCHEDULE: "VIDEOHUB_OUTPUT_SCHEDULE",
    PERMISSION_VIDEOHUB_PUSHBUTTONS_EDIT: "VIDEOHUB_PUSHBUTTONS_EDIT",
    PERMISSION_VIDEOHUB_EDIT: "VIDEOHUB_EDIT",
    PERMISSION_USER_EDIT: "USER_EDIT",
}